#cloud-config
hostname: ${hostname}

users:
    - default # Really important, keeps the default ubuntu user with the AWS key_pair
    - name: vault
      gecos: service vault user
      shell: /usr/sbin/nologin
      system: true
      lock_passwd: true

# Adding Hashicorp repo
apt:
  sources:
    hashicorp.list:
      source: "deb [arch=amd64] https://apt.releases.hashicorp.com $RELEASE main"
      keyid: A621E701

# Installing vault enterprise, jq, terraform and awscli
packages:
  - [vault-enterprise, "${vault_version}"]
  - jq
  - terraform
  - awscli

package_upgrade: false
package_update: true

# Adding the new hostname to /etc/hosts
manage_etc_hosts: true
fqdn: "${hostname}"

timezone: ${timezone}

final_message: "The system is finally up, after $UPTIME seconds"
